backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "content/ctiHome.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Day Passes with Gear"
            name: "day_gear"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "desc", widget: "text" }
              - { label: "Price", name: "price", widget: "number" }
          - label: "Day Passes without Gear"
            name: "day_noGear"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "desc", widget: "text" }
              - { label: "Price", name: "price", widget: "number" }
          - label: "Bundles"
            name: "bundle"
            widget: object
            fields:
              - label: "Passes"
                name: "passes"
                widget: list
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Description", name: "desc", widget: "text" }
                  - { label: "Price", name: "price", widget: "number" }
              - label: "Memberships"
                name: "memberships"
                widget: list
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Description", name: "desc", widget: "text" }
                  - { label: "Price", name: "price", widget: "number" }
      - label: "TestMDX"
        name: "testmdx"
        file: "content/newToClimbing.mdx"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Examples"
            name: "examples"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
